server:
  port: 8080
  env: development

database:
  host: localhost
  port: 5432
  user: postgres
  password: your_password_here
  name: ecommerce
  sslmode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

jwt:
  secret: your_jwt_secret_here
  expiration: 24h

services:
  payment:
    url: http://localhost:8084
    api_key: your_payment_api_key_here
  order:
    url: http://localhost:8082
  product:
    url: http://localhost:8083
  user:
    url: http://localhost:8081

metrics:
  enabled: true
  port: 9090

logging:
  level: debug
  format: json

cors:
  allowed_origins:
    - http://localhost:3000
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Content-Type
    - Authorization
  max_age: 300 